version: '3.3'
services:

  app: &app_base
    build:
      context: .
    env_file:
      - "${ENV_FILE}"
    ports:
      - "80:3000"

  worker:
    <<: *app_base
    command: bundle exec shoryuken -C config/shoryuken.yml -R
    ports: []
