# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  queues:
    lai_pdf_generation: <%= ENV["LAI_PDF_GENERATION_QUEUE"] %>
    plip_changed_sync: <%= ENV["PLIP_CHANGED_SYNC_QUEUE"] %>
    petition_notifier: <%= ENV["PETITION_NOTIFIER_QUEUE"] %>
    petition_publisher: <%= ENV["PETITION_PUBLISHER_QUEUE"] %>
    petition_pdf_generation: <%= ENV["PETITION_PDF_GENERATION_QUEUE"] %>
    petition_mobile_sync: <%= ENV["PETITION_MOBILE_SYNC_QUEUE"] %>
    petition_cover_generation: <%= ENV["PETITION_COVER_GENERATION_QUEUE"] %>
    petition_share_link_generation: <%= ENV["PETITION_SHARE_LINK_GENERATION_QUEUE"] %>

  buckets:
    petition_cover: <%= ENV["PETITION_COVER_BUCKET"] %>
    petition_pdf: <%= ENV["PETITION_PDF_BUCKET"] %>
    mudamos_video: <%= ENV["MUDAMOS_VIDEO_BUCKET"] %>
    lai_pdf: <%= ENV["LAI_PDF_BUCKET"] %>

  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    region: <%= ENV["AWS_REGION"] %>

  apis:
    mobile:
      url: <%= ENV["MOBILE_API_URL"] %>
      secret: <%= ENV["MOBILE_API_SECRET"] %>
      timeout: <%= ENV["MOBILE_API_TIMEOUT"] || 10 %>
    lai:
      auth_token: <%= ENV["WEB_AUTH_TOKEN"] %>

  http_cache:
    api_expires_in: <%= ENV["API_CACHE_EXPIRES_IN"] || 1 %>

  mobile_app_id:
    ios: <%= ENV["MOBILE_API_ID_IOS"] || "1071484944" %>

  mobile_app:
    store_page:
     android: <%= ENV["MOBILE_APP_STORE_PAGE_ANDROID"] %>
     ios:  <%= ENV["MOBILE_APP_STORE_PAGE_IOS"] %>
    signed_plip_tag:
      prefix: signed-plip-

  firebase:
    api_key: <%= ENV["FIREBASE_API_KEY"] %>
    dynamic_link_domain: <%= ENV["FIREBASE_DYNAMIC_LINK_DOMAIN"] %>
    android_package: <%= ENV["FIREBASE_ANDROID_PACKAGE"] %>
    ios_package: <%= ENV["FIREBASE_IOS_PACKAGE"] %>

development:
  <<: *default
  secret_key_base: 1b3558fabd17afc3400af94e9ceee4d9bf6078dd37d29827ea39a1063a8541fe5b2b668ddd28f9084d9af6cd2bc9c78afc3656ea4214b48e4e7385fb5f0da850

test:
  <<: *default
  secret_key_base: ec4cedf9f5a4959e7937380b017c59bb456824f1a1b74c93e3919514754ae35cf8cad1f0cec7c204aa1e7c2a88866cca09f4135906c5f545c9729fdb24ebdc77

staging:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
