concurrency: <%= ENV["SHORYUKEN_CONCURRENCY"] %>
delay: <%= ENV["SHORYUKEN_DELAY"] %>
queues:
  - [ <%= ENV["PLIP_CHANGED_SYNC_QUEUE"] %>, <%= ENV["PLIP_CHANGED_SYNC_QUEUE_PRIORITY"] || 1 %> ]
  - [ <%= ENV["PETITION_PDF_GENERATION_QUEUE"] %>, <%= ENV["PETITION_PDF_GENERATION_QUEUE_PRIORITY"] || 1 %> ]
  - [ <%= ENV["PETITION_MOBILE_SYNC_QUEUE"] %>, <%= ENV["PETITION_MOBILE_SYNC_QUEUE_PRIORITY"] || 1 %> ]
  - [ <%= ENV["PETITION_PUBLISHER_QUEUE"] %>, <%= ENV["PETITION_PUBLISHER_QUEUE_PRIORITY"] || 1 %> ]
  - [ <%= ENV["PETITION_NOTIFIER_QUEUE"] %>, <%= ENV["PETITION_NOTIFIER_QUEUE_PRIORITY"] || 1 %> ]
  - [ <%= ENV["PETITION_COVER_GENERATION_QUEUE"] %>, <%= ENV["PETITION_COVER_GENERATION_QUEUE_PRIORITY"] || 1 %> ]
  - [ <%= ENV["PETITION_SHARE_LINK_GENERATION_QUEUE"] %>, <%= ENV["PETITION_SHARE_LINK_GENERATION_QUEUE_PRIORITY"] || 1 %> ]
